### ISSUE TITLE
Windows Still Uses "Generic USB Joystick" Driver

### ISSUE THREAD

**Issue by ni554n** [alessandroasm/generic-usb-gamepad-vibration-driver#1]
Hey man, thanks for the effort; really appreciate it. But I'm unable to use this driver.

I've the same controller with similar hardware ID. By default it uses **_Generic  USB Joystick_**. I've removed generic driver, installed this one and connected the gamepad again. But nothing happens. Windows still use _Generic  USB Joystick_. 

So, what to do here?

**Comment by alessandroasm** [comment]
Hello ni554n,

Since the default HID driver is good enough to handle the input, I wrote only the ForceFeedback (output) driver. In other words, Windows will still use the default driver for it.

## How does it work then?
When a application supports force feedback, it will use DirectInput to load and use the driver. DirectInput searches for the driver in Windows registry at the following path (assuming it is a 64-bit application):
![image](https://cloud.githubusercontent.com/assets/2970975/22026233/f9db81b2-dcae-11e6-9dfc-3f5778468347.png)
If things are set up correctly, the application will load the proper dll
![image](https://cloud.githubusercontent.com/assets/2970975/22026398/6f52b1a4-dcaf-11e6-95de-e437d9d660c2.png)

## What could go wrong
I still have to tweak the setup file. Maybe it didn't registered the dlls correctly. You can do this manually using the following steps:
- Open an **administrator** prompt
- Navigate to installation directory (defaults to c:\Windows\GenericFFBDriver)
- regsvr32 GenericFFBDriver64.dll
- c:\Windows\SysWOW64\regsvr32.exe GenericFFBDriver32.dll

**Comment by ni554n** [comment]
Thanks. It works, but only with **cemu**. I tried with [Xbox 360 Controller Emulator](http://www.x360ce.com), but unfortunately vibration not working.

Btw, I have a question, can you play **Windows Store** games with this controller without any input binding?

**Comment by alessandroasm** [comment]
The analog button is working fine on my controller. When the light is on, both the analog sticks work as analog inputs (the game knows how much you are pushing them). I always use it on analog mode.

I've tested the xbox 360 controller emulator on assassin's creed unity and it works when I selected the following options:
![image](https://cloud.githubusercontent.com/assets/2970975/22038544/615c52fa-dcda-11e6-9976-93c1d1c8b191.png)

Vibration is not working as expected though... I'm gonna look further into this
